### ISSUE TITLE
Функціональні вимоги

### ISSUE THREAD

**Issue by SolomiiaMatiichuk** [PE-Pmi-32-2021/love-pets#1]
Описати основні функціональні вимоги до проекту.

**Comment by SolomiiaMatiichuk** [comment]
•  Створення профілю тварини
•  Можливість створення нагадувань в календарі

**Comment by IvannaaTR** [comment]
•  Пошук інформації про тварин
•  Пошук тварин за категоріями
•  Заповнення анкети для вибору свого улюбленця

**Comment by Loathriel** [comment]
Виглядає добре, приймаєм
