### ISSUE TITLE
Нефункціональні вимоги

### ISSUE THREAD

**Issue by IrynaSloboda** [PE-Pmi-32-2021/love-pets#3]

**Comment by IrynaSloboda** [comment]
Нефункціональні вимоги:
•	Локалізація українською та англійською мовами
•	Буде представлено 5 категорій тварин (собаки, коти, гризуни, птахи, рептилії)
•	Інформація про тварин включає в себе особливості догляду та лікування, характер та фізичні характеристики
•	До нагадувань можна додавати опис (до 250 символів)

**Comment by Loathriel** [comment]
•  Нагадування можуть бути періодичними (щоденні, щотижневі, щомісячні, щорічні) та одноразовими на конкретну дату
•  Залежно від типу нагадування (прийом ліків, похід до ветеринара, прийом їжі і тд.) можна обирати колір події
•  Локальна база даних для збереження нагадувань та інформації про тварин користувача
•  Користувач може створити до 5-ти профілів тварин

**Comment by SolomiiaMatiichuk** [comment]
Looks good. No remarks from my side
