### ISSUE TITLE
Add screenshots of clean-up process

### ISSUE THREAD

**Issue by Loathriel** [PE-Pmi-32-2021/love-pets#34]

**Comment by Loathriel** [comment]
![Before_clean-up](https://user-images.githubusercontent.com/74023154/141849073-88d8555f-dcc1-4dde-a9b2-920d235c19bf.png)
![After_clean-up](https://user-images.githubusercontent.com/74023154/141849077-d6d9b4a4-1e87-4875-8907-f687181d0d7d.png)

**Comment by Loathriel** [comment]
![Final_result](https://user-images.githubusercontent.com/74023154/141849358-d1baf729-797c-4339-bccb-a233ce509243.png)

**Comment by IrynaSloboda** [comment]
No mistakes, that's great!
