### ISSUE TITLE
usecase diagram

### ISSUE THREAD

**Issue by IrynaOmeliukh** [PE-Pmi-32-2021/love-pets#4]
Власник домашнього улюбленця:
* Пошук інформації про тварин
* Пошук тварин за категоріями
* Заповнення анкети для пошуку тварини
* Створення нагадування про подію 
* Створення профілю домашнього улюбленця

Людина, яка шукає домашнього улюбленця:
* Пошук інформації про тварин
* Пошук тварин за категоріями
* Заповнення анкети для пошуку тварини

![image_2021-09-23_22-20-00](https://user-images.githubusercontent.com/80892358/134627768-18439c72-7add-47fd-bb78-49b03d5aff43.png)

**Comment by IvannaaTR** [comment]
Looks good.
