### ISSUE TITLE
Створити дві сторінки wireframe

### ISSUE THREAD

**Issue by Loathriel** [PE-Pmi-32-2021/love-pets#5]
Створити сторінки для довгих питань анкети та для інформації про тварин

**Comment by Loathriel** [comment]
![Сторінка анкети 2](https://user-images.githubusercontent.com/74023154/135504262-988e2ff3-b5f4-439a-9421-6f29928b16b0.jpg)
![Сторінка інформації](https://user-images.githubusercontent.com/74023154/135504266-4595f73f-e909-4fbd-94ea-770a13c59b7d.jpg)

**Comment by IrynaSloboda** [comment]
Ревю зроблено, все добре, приймаю
