### ISSUE TITLE
створити сторінки wireframe для профілю, результатів та календаря

### ISSUE THREAD

**Issue by SolomiiaMatiichuk** [PE-Pmi-32-2021/love-pets#6]

**Comment by SolomiiaMatiichuk** [comment]
![Сторінка профілю](https://user-images.githubusercontent.com/67965202/135504870-830fa34a-5ebe-4dea-933c-e74d9069e248.jpg)
![Сторінка результату](https://user-images.githubusercontent.com/67965202/135504928-84a892e2-80a8-48a8-985c-42fe1bf62899.jpg)
![Сторінка календар](https://user-images.githubusercontent.com/67965202/135504969-cdaec4fc-0bec-4d13-b15b-53fde32f020d.jpg)

**Comment by IvannaaTR** [comment]
Looks good!
