### ISSUE TITLE
Створити wireframes для двох сторінок аплікації

### ISSUE THREAD

**Issue by IrynaSloboda** [PE-Pmi-32-2021/love-pets#7]
Сторінка анкети для типу з довгими питаннями та сторінка тваринок в категорії

**Comment by IrynaSloboda** [comment]
![Сторінка анкети 1](https://user-images.githubusercontent.com/77804156/135504821-0ecc7a53-5646-4078-ac8a-85ebb8b093f8.jpg)
![Сторінка елементів](https://user-images.githubusercontent.com/77804156/135504825-d0484dab-30ff-48f4-9b24-53e5c1636d4e.jpg)

**Comment by Loathriel** [comment]
Seems good to go
