### ISSUE TITLE
Створити сторінки wireframes для входу, головну сторінку та сторінку категорій.

### ISSUE THREAD

**Issue by IvannaaTR** [PE-Pmi-32-2021/love-pets#8]

**Comment by IvannaaTR** [comment]
![Сторінка всіх](https://user-images.githubusercontent.com/90395095/135505169-5a2d92bf-fd84-4dc0-bc98-ca3fcece2e20.jpg)
![Сторінка входу](https://user-images.githubusercontent.com/90395095/135505175-325b0848-87d1-4ffc-b358-107c978f3d44.jpg)
![Сторінка категорій](https://user-images.githubusercontent.com/90395095/135505178-2003cf4d-4f53-4dcc-be46-53dfc19f25f2.jpg)

**Comment by SolomiiaMatiichuk** [comment]
Result of review - very good. No remarks
