### ISSUE TITLE
Poll to chose a pet

### ISSUE THREAD

**Issue by IrynaOmeliukh** [PE-Pmi-32-2021/love-pets#9]

**Comment by IrynaOmeliukh** [comment]
https://docs.google.com/forms/d/e/1FAIpQLSckqdM1mP6pUVDi7jChhIAc5r8Ri2o2m_4HWQzXv_u0FJXBVg/viewform?usp=sf_link

**Comment by IrynaSloboda** [comment]
Ревю проведено, анкета приймається
